---

- hosts: localhost
  connection: local
  gather_facts: False
  vars:

    app:
      id: nginx
      instances: 1
      cpus: 1
      mem: 128
      container:
          type: "DOCKER"
          docker:
            image: "nginx:latest"
            network: "BRIDGE"
            privileged: false
            forcePullImage: true
            portMappings:
            - containerPort: 80
              hostPort: 0
      healthChecks: []
      upgradeStrategy:
          maximumOverCapacity: 0
          minimumHealthCapacity: 0
      labels:
          "MARATHON_SINGLE_INSTANCE_APP": "true"

  # TODO: Ensure marathon python module is installed on the control machine
  # pre_tasks:
  #   - shell: pip install -r roles/marathon-deploy/requirements.txt

  roles:
    - marathon-deploy
  tasks:
    - name: run Nginx on marathon
      marathon: uri=http://{{ hostvars['master01.tera.local'].ansible_host }}:8080 app='{{ app | to_json }}' state=present
